### PR TITLE
Bump rocksdb version to 5.10.2

### PR DESCRIPTION
**Pull request by ongardie-ebay**

### CODE REVIEW

**Comment by spacejam** [comment]
thanks diego! I'll cut a new version with this today :)

**Comment by spacejam** [comment]
crate versions `0.8.3` and `0.9.0` have been cut with these changes included!

**Comment by ongardie-ebay** [comment]
Thanks @spacejam. You can expect a couple more PRs from me early next week. I'd have told you to hold off on the release but you were too quick :)

**Comment by spacejam** [comment]
@ongardie-ebay wohoo awesome! We can keep rolling forward as new stuff comes in :) I'm happy to burn versions quickly as new stuff lands.

**Pull request merged**
