### PR TITLE
More idiomatic iterators?

### PR DESCRIPTION
**Pull request by petehunt**
I had an issue where I wanted to store a reference to a `SubDBIterator` on a struct. Because it's created from a `DBIterator`, I ran into an issue where I couldn't store a reference to both the iterator and sub-iterator on the same struct, and couldn't get the `DBIterator` instance to live long enough (see: https://internals.rust-lang.org/t/self-referencing-structs/418)

This PR merges `SubDBIterator` into `DBIterator`. While I was working on it, I fixed a few todos in the code (the DB lifetime one was also confusing).

I can't think of a better name for the `IteratorMode` enum. Also, I am a rust newb :)

### CODE REVIEW

**Comment by rscnt** [comment]
:+1:

**Comment by spacejam** [comment]
Sorry for the slow feedback, I've been avoiding github for the last few days!  The code looks good, can you update the readme to make use of the new syntax?  Then I'll merge and cut a new version with these improvements!  Thank you for the pull request!

**Comment by petehunt** [comment]
Updated the README. Please let me know if you see anything weird!

**Comment by spacejam** [comment]
Thanks!  I'll cut `0.3.0` now with your improvements!

**Pull request merged**
