### PR TITLE
Renamed 'librocksdb-sys' to 'rocksdb-sys'.

### PR DESCRIPTION
**Pull request by alexreg**
Also added back `error::Error` impl.

### CODE REVIEW

**Comment by spacejam** [comment]
I renamed the FFI to be librocksdb-sys so that we could upload it to crates.io, as rocksdb-sys was already taken.

**Comment by spacejam** [comment]
It's ugly for sure, but it works.

**Comment by alexreg** [comment]
Oh, sorry! I forgot about this.

(I presume the previous owner wasn’t willing to give up the name…)

I’ll let you put in the error::Error impl yourself then.

**Comment by alexreg** [comment]
(And actually, it might be worth accepting this PR, and keeping the dir name as rocksdb-sys, and only change the *crate* name. But up to you of course.)

**Comment by spacejam** [comment]
I'd like to keep them in-sync for now to minimize breakage due to forgotten naming. It's nice to keep all usage of a thing aligned to as few names as possible, to reduce effort to understand usage while doing future work on it. I appreciate this effort, but I'm going to close this PR now. Master now has the error::Error impl in it!

**Comment by alexreg** [comment]
The problem wasn’t master having the Error impl in it, but rather the 0.5.0 branch.

**Comment by alexreg** [comment]
Oh, ignore me. You merged 0.5.0 into master. Probably worth remotely deleting the 0.5.0 branch then. :-)

**Pull request closed without merging**
