### PR TITLE
Link with system rocksdb and snappy libs through envvars

### PR DESCRIPTION
**Pull request by ozkriff**
This PR adds 4 env variables: `ROCKSDB_LIB_DIR`, `SNAPPY_LIB_DIR`, `ROCKSDB_STATIC` and `SNAPPY_STATIC`.

What do you think of this? :)

(related to https://github.com/spacejam/rust-rocksdb/issues/138)

### CODE REVIEW

**Comment by DarkEld3r** [comment]
I want to add more details: we are currently using [fork](https://github.com/exonum/exonum_rocksdb) of `rust-rocksdb` for our [project](https://github.com/exonum/exonum), but we prefer to switch to your crate. Still we need several things to be done and this is one of them. Thus, we are very interested in any feedback.

**Comment by spacejam** [comment]
Sorry for the huge delay on this! Just started a new job and I've been getting used to a new schedule. I like this approach! I'll cut a new version in a few minutes that includes this change :)

**Comment by spacejam** [comment]
I've published rocksdb `0.10.0` which includes these changes!

**Comment by DarkEld3r** [comment]
@spacejam Thank you! Probably, there will be several more things that we need before switching to your crate, but we are looking forward to that.

**Comment by jonhoo** [comment]
It'd be really neat if `rocksdb-sys` checked if `rockdb` and `snappy` were available in the standard OS locations too. It's a little unfortunate to have to pass custom environment variables every time we build even though those libraries are installed system-wide.

**Comment by jonhoo** [comment]
Tangentially related to my comment above — this should probably be mentioned in the docs.

**Pull request merged**
