### PR TITLE
0.5.0

### PR DESCRIPTION
**Pull request by spacejam**

### CODE REVIEW

**Comment by spacejam** [comment]
@kaedroho @alexreg @jezell @dgrnbrg @vmx @ngaut 

RocksDB is now vendored.

Writeable is gone, as we've learned that WriteBatch requires external synchronization, hence its methods are now `&mut self`.

Currently available from crates.io as `0.5.0-rc.1`.

Any concerns, comments, desired breaking API changes before this gets cut?

**Comment by kaedroho** [comment]
Nice work @spacejam, this looks great to me.

I've just updated the changelog for 0.5.0, bringing the breaking changes to the top as well. I hope I haven't missed anything: https://github.com/spacejam/rust-rocksdb/pull/94

**Comment by vmx** [comment]
@spacejam Looks good to me, thanks for pinging.

**Comment by spacejam** [comment]
Thanks everyone for contributing to this! Cutting 0.5.0 now :)

**Pull request merged**
