### PR TITLE
Added explicit `CompareFn` type for comparator function.

### PR DESCRIPTION
**Pull request by alexreg**
Changed return type of comparator function from `i32` to `std::cmp::Ordering`.

### CODE REVIEW

**Comment by alexreg** [comment]
By the way, what do you think about changing all the `Default` impls to inherent `new` functions? This would be more in line with the stdlib, and you could also then implement `Default` for `DB`, but have it replace the `open_default` method. Slightly more ergonomic, if you ask me.

**Comment by alexreg** [comment]
@spacejam Mind taking a look at this? :)

**Comment by spacejam** [comment]
Sorry for the delay! This is great! Thank you for adding this functionality and cleaning things up :) 

RE: `open_default()`, `default()`, `new()`, I'm in favor of following the stdlib convention of a `Default` impl that just calls `new()` under the hood for most types. I'm not sure about `Default` for `DB` though, because RocksDB requires a path for persistence, and it feels a little weird to me to assume a path here.  Do you know if other wrappers provide default paths?

**Comment by alexreg** [comment]
Ah, silly me. I meant a `Default` for `DBOptions`.

By the way, minor aesthetic point: should we change `DB`, `DBOptions`, etc. to `Db`, `DbOptions`, etc.? This seems to be the Rust casing convention, even for abbreviations.

**Comment by spacejam** [comment]
Yeah, I'm in favor of adding a `new()` function for `Options` and changing `DB` to `Db` etc... in the future to be more in-line with the stdlib conventions!

**Comment by alexreg** [comment]
Great. I will try to submit a PR for this in the near future…

**Comment by alexreg** [comment]
Been going over some of the code lately, and remembered you return boxed slices rather than vectors from iterators. Is there any specific reason for this?

**Pull request merged**
