### PR TITLE
Expose WriteOptions

### PR DESCRIPTION
**Pull request by cstorey**
Hi.

I needed the option for synchronous writes on a recent project, so I've exposed a `WriteOptions` type, along with variants of `DB#put`, etc that accept that type.

I'm not quite sure what you're after in terms of testing, so if you could clarify that, that'd be great.

Thanks,

### CODE REVIEW

**Comment by spacejam** [comment]
@cstorey thank you for adding this! I just merged an earlier PR that reformatted some things that are causing conflict, and I will merge this PR as soon as they are resolved.

**Comment by cstorey** [comment]
Thanks; I've applied the same formatting to my branch.

**Comment by spacejam** [comment]
LGTM, thank you for this contribution!

**Comment by cstorey** [comment]
Thanks.

**Pull request merged**
